### ISSUE TITLE
Invalid API key error after enabling session replay

### ISSUE THREAD

**Issue by Mohammad-Resonanz** [amplitude/AmplitudeSessionReplay-Android#1]
We've been using Amplitude for quite a while and we decided to give session replays a shot.
After updating the Amplitude config, events are not logged and I'm getting error 400 "invalid key" but API key is not changed.
This is my new config:

```
amplitude = Amplitude(
                Configuration(
                    apiKey = apiKey,
                    context = context,
                    serverZone = ServerZone.EU,
                    autocapture = autocaptureOptions {
                        +appLifecycles
                        +screenViews
                        +deepLinks
                        +sessions
                    },
                ),
            )
                .apply {
                    this.add(SessionReplayPlugin(sampleRate = 0.5))
                }
```

**Comment by izaaz** [comment]
@Mohammad-Resonanz, Got your message from Katie as well. Our API keys are tied to a region. So if you got an API key issued from analytics.amplitude.com, you'll need to use serverZone 'US' and not 'EU'. 

If you'd like to send data to our EU cluster, you'll need to create an account in analytics.eu.amplitude.com and get an API key from there.

**Comment by Mohammad-Resonanz** [comment]
Thanks @izaaz that explains it.
I'll close this issue.
